-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 1️. Customer Insights

-- How many unique customers have placed orders?
select distinct cust_id,cust_name from customers t1
join orders t2
using(cust_id);

-- Which customers have placed the highest number of orders?

select cust_id,cust_name,count(*) as no_of_orders from customers t1
join orders t2
using(cust_id)
group by cust_id
order by count(*) desc
limit 3;
-- What is the total and average purchase value per customer?
select cust_name,sum(total_price) as total,round(sum(total_price)/sum(quantity),2) as average_purchase from customers t1
join orders t2
using (cust_id)
join order_details t3
using(ord_id)
group by t1.cust_id;

-- Who are the top 5 customers by total purchase amount?

select cust_name,sum(total_price) as total from customers t1
join orders t2
using (cust_id)
join order_details t3
using(ord_id)
group by t1.cust_id
order by total desc
limit 5;

-- 2. Product Performance

-- How many products exist in each category?


select cat_name,count(*) as no_of_products from categories
join products
using(cat_id)
group by cat_id;

-- What is the average price of products by category?

select cat_name,avg(price) from categories t1
join products t2
using(cat_id)
group by cat_id;

-- Which products have the highest total sales volume (by quantity)?

select prod_name,sum(quantity) as total_sales from products t1
join order_details t2
using(prod_id)
group by t1.prod_id
order by total_sales desc
limit 3;

-- What is the total revenue generated by each product?
select prod_name,sum(total_price) as revenue from products t1
join order_details t2
using(prod_id)
group by t1.prod_id;

-- How do product sales vary by category and supplier?
SELECT sup_name,
       cat_name,
       SUM(quantity)
FROM supplier
JOIN products
USING (sup_id)
JOIN categories
USING (cat_id)
JOIN order_details
USING (prod_id)
GROUP BY sup_id, cat_name;
-- 3. Sales and Order Trends

-- How many orders have been placed in total?

select count(*) as total_orders from orders o1
join order_details o2
using(ord_id);

-- What is the average value per order?
select sum(total_price)/count(*) as average_value_per_order from orders t1
join order_details t2
using(ord_id);

-- On which dates were the most orders placed?
select order_date,count(*) as total_no_of_orders from orders t1
join order_details t2
group by order_date
order by total_no_of_orders desc
limit 1;

-- What are the monthly trends in order volume and revenue?

select monthname(dates),sum(total_price) as revenue,count(*) as no_orders from
 (select *,str_to_date(order_date,"%m/%d/%y") as dates from orders) t
join order_details using(ord_id)
group by monthname(dates);
-- How do order patterns vary across weekdays and weekends?
with cte as (select *,(case when weekday(dates)<5 then "weekday"
         else "weekend" end) as days from 
         (select *,str_to_date(order_date,"%m/%d/%y") as dates from orders) t)
select days,count(*) as no_of_orders from cte
join order_details
using(ord_id)
group by days;
-- 4️. Supplier Contribution
-- How many suppliers are there in the database?
select count(*) as no_of_suppliers from supplier;
-- Which supplier provides the most products?
select sup_name,count(*) as no_of_products from supplier
join products
using(sup_id)
group by sup_id
order by no_of_products desc
limit 1;

-- What is the average price of products from each supplier?
select sup_name,prod_name,avg(price) as average from supplier
join products
using(sup_id)
group by sup_id,prod_id;
-- Which suppliers contribute the most to total product sales (by revenue)?
select sup_name,sum(total_price) as revenue from supplier t1
join products t2
join order_details t3
using(prod_id)
group by t1.sup_id
order by revenue desc
limit 1;
-- 5. Employee Performance
-- How many employees have processed orders?
select count(distinct emp_id) from employees
join orders
using(emp_id);
-- Which employees have handled the most orders?
select emp_name,count(*) as no_of_orders from employees
join orders
using(emp_id)
group by emp_id
order by no_of_orders desc limit 1;
-- What is the total sales value processed by each employee?
select emp_name ,sum(total_price) as sales_value from employees t1
join orders t2
using(emp_id)
join order_details t3
using (ord_id)
group by emp_id;
-- What is the average order value handled per employee?
select emp_name,avg(total_price) as average from employees t1
join orders t2
using(emp_id)
join order_details t3
using (ord_id)
group by emp_id;
-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
select * from order_details
where quantity*each_price=total_price;
-- quantity*each_price=total_price

-- What is the average quantity ordered per product?
select prod_name,avg(quantity) as average from products
join order_details
using(prod_id)
group by prod_id;

-- How does the unit price vary across products and orders?

select prod_name,
AVG(each_price) AS avg_unit_price,
       MIN(each_price) AS min_unit_price,
       MAX(each_price) AS max_unit_price,
       COUNT(*) AS times_ordered from order_details
join products
using(prod_id)
group by prod_name;


